# Generated by Django 5.1 on 2024-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_customusermodel_role_alter_settings_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=50),
        ),
    ]
