# Generated by Django 5.1 on 2024-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_remove_teammember_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer')], max_length=50),
        ),
    ]
