# Generated by Django 5.1 on 2024-09-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_customusermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='account_level',
            field=models.CharField(default='Developer', max_length=20),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='team',
            field=models.CharField(default='Video Game Consoles', max_length=50),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
