# Generated by Django 5.1 on 2024-09-20 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetandcategory',
            name='user_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
