# Generated by Django 5.1 on 2024-09-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_customusermodel_account_level_customusermodel_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
