# Generated by Django 5.1 on 2024-09-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_expensecategory_userprofile_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetandcategory',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.expensecategory'),
        ),
        migrations.AlterField(
            model_name='teamandsetting',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
