# Generated by Django 5.1 on 2024-09-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetandcategory',
            options={'permissions': [('can_create_budget', 'Can create budgets'), ('can_read_budget', 'Can read budgets'), ('can_update_budget', 'Can update budgets')]},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_create_transaction', 'Can create transactions'), ('can_read_transaction', 'Can read transactions'), ('can_update_transaction', 'Can update transactions')]},
        ),
    ]
