# Generated by Django 5.1 on 2024-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_transaction_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamandsetting',
            name='work_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
